config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'persons/thema'
  get 'persons/question'
  resources :questions
  resources :posts do
    resources :microposts
  end

  get '/questions_result', to: 'questions#result_index'
  post '/posts/:post_id/microposts/:id/like', to: 'microposts#like', as: :like
  post '/questions/:id/answer/:answer_id', to: 'questions#answer', as: :answer_question
  root 'static_pages#home'

  get '/users', to: 'users/registrations#new'

  get   '/help',    to: 'static_pages#help'
  get   '/contact', to: 'static_pages#contact'
  get   '/about',   to: 'static_pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id='error_explanation'>
  <div class='alert alert-danger'>
    <%= "#{object.errors.count} 箇所の入力誤りがあります" %>
  </div>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_post_index.html.erb
<% @posts.each do |post| %>
<% if user_signed_in? && current_user.id == post.user_id %>
<%= link_to '編集', edit_post_path(post), class: "post_btn continer  bg-white shadow-sm" %>

<%= link_to '削除', post_path(post), method: :delete, data: { confirm: '本当に削除してもよろしですか?' }, class: "post_btn continer  bg-white shadow-sm" %>
<% end %>
投稿<b><%= Micropost.where(post_id: post.id).count %></b>件　
残り　<b><b><b><%=  (post.end_date - Date.today).numerator %></b></b></b>日
<div class="continer DivLink  p-1 bg-white rounded shadow">
  <div class='main'>
    <div class='row'>

      <div class="col-4">・区分</div>
      <div class='col-8'>
        <% if post.section.include? "ビ" %>
        <div class='section b'>ビ</div>
        <% end %>

        <% if post.section.include? "情" %>
        <div class='section j'>情</div>

        <% end %>
        <% if post.section.include? "医" %>
        <div class='section i'>医</div>
        <% end %>

        <% if post.section.include? "公" %>
        <div class='section g'>公</div>
        <% end %>

        <% if post.section.include? 'イ' %>
        <div class='section e'>イ</div>
        <% end %>
      </div>
    </div>
    <div class='row'>
      <div class='col-4'>・テーマ</div>
      <div class="col-8">
        <b><%= post.title %></b>
      </div>
    </div>
    <div class='row'>
      <div class='col-4'>・開始日</div>
      <div class="col-8">
        <%= post.start_date%>
      </div>
    </div>
    <div class='row'>
      <div class='col-4'>・終了日</div>
      <div class="col-8">
        <%= post.end_date%>（あと<%=  (post.end_date - Date.today).numerator %>日）
      </div>
    </div>
    <div class='row'>
      <div class='col'>
        <%= link_to 'このテーマに提案する', post_microposts_path(post), class: "btn btn-lg btn-primary thema" %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_post_result_index.html.erb
<% @posts_result.each do |post| %>

投稿<b><%= Micropost.where(post_id: post.id).count %></b>件
<div class="continer DivLink  p-1 bg-white rounded shadow">
  <div class='main'>
    <div class='row'>

      <div class="col-4">・区分</div>
      <div class='col-8'>
        <% if post.section.include? "ビ" %>
        <div class='section b'>ビ</div>
        <% end %>

        <% if post.section.include? "情" %>
        <div class='section j'>情</div>

        <% end %>
        <% if post.section.include? "医" %>
        <div class='section i'>医</div>
        <% end %>

        <% if post.section.include? "公" %>
        <div class='section g'>公</div>
        <% end %>

        <% if post.section.include? 'イ' %>
        <div class='section e'>イ</div>
        <% end %>
      </div>
    </div>
    <div class='row'>
      <div class='col-4'>・テーマ</div>
      <div class="col-8">
        <b><%= post.title %></b>
      </div>
    </div>
    <div class='row'>
      <div class='col-4'>・開始日</div>
      <div class="col-8">
        <%= post.start_date%>
      </div>
    </div>
    <div class='row'>
      <div class='col-4'>・終了日</div>
      <div class="col-8">
        <%= post.end_date%>
      </div>
    </div>

    <div class='row'>
      <div class='col'>
        <%= link_to '投票結果を閲覧する', post_microposts_path(post), class: "btn btn-result btn-lg thema" %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_question_index.html.erb
<% @questions.each do |question| %>
<% if user_signed_in? && current_user.id == question.user_id %>
<%= link_to '編集', edit_question_path(question), class: "post_btn continer  bg-white shadow-sm" %>

<%= link_to '削除', question_path(question), method: :delete, data: { confirm: '本当に削除してもよろしですか?' }, class: "post_btn continer  bg-white shadow-sm" %>
<% end %>
終了まで残り　<b><%= (question.end_date - Date.today).numerator %></b>日
<div class="continer DivLink  p-1 bg-white rounded shadow">
  <div class='main'>
    <div class='row'>

      <div class="col-3">・区分</div>
      <div class='col-9'>
        <% if question.section.include? "ビ" %>
        <div class='section b'>ビ</div>
        <% end %>

        <% if question.section.include? "情" %>
        <div class='section j'>情</div>

        <% end %>
        <% if question.section.include? "医" %>
        <div class='section i'>医</div>
        <% end %>

        <% if question.section.include? "公" %>
        <div class='section g'>公</div>
        <% end %>

        <% if question.section.include? 'イ' %>
        <div class='section e'>イ</div>
        <% end %>
      </div>
    </div>
    <div class='row hr'>
      <div class='col-3'>・件名</div>
      <div class="col-9">
        <h3><%= question.title %></h3>
      </div>
    </div>
    <div class='row'>
      <div class='col-3'>・内容</div>
      <div class="col-9">
        <b><%= question.content %></b>
      </div>
    </div>
    <div class='row'>
      <div class='col-3'>・開始日</div>
      <div class="col-9">
        <%= question.start_date%>
      </div>
    </div>
    <div class='row'>
      <div class='col-3'>・終了日</div>
      <div class="col-9">
        <%= question.end_date%>（あと<b><%= (question.end_date - Date.today).numerator %></b>日）
      </div>
    </div>

    <div class='row'>
      <% if !(answer = @answer.find_by(question_id: question.id)) %>
      <div class='col'>
        <%= link_to answer_question_path(question.id, 1) ,class: "btn btn-lg btn-primary thema", method: :post do %>
        賛成する
        <span class="badge badge-pill badge-light"><%= Answer.where(question_id: question.id, answer: true).count%></span>
        <% end %>
      </div>
      <div class='col'>
        <%= link_to answer_question_path(question.id, 0) ,class: "btn btn-lg btn-danger thema", method: :post do %>
        反対する
        <span class="badge badge-pill badge-light"><%= Answer.where(question_id: question.id, answer: false).count%></span>
        <% end %>
      </div>
      <% elsif answer.answer %>
      <%# 賛成済み %>
      <div class='col'>
        <button class="btn-lg btn-secondary thema">賛成済み <span class="badge badge-pill badge-light"><%= Answer.where(question_id: question.id, answer: true).count %></span></button>
      </div>
      <div class='col'>
        <%= link_to answer_question_path(question.id, 0) ,class: "btn btn-lg btn-danger thema", method: :post do%>
        反対する
        <span class="badge badge-pill badge-light"><%= Answer.where(question_id: question.id, answer: false).count%></span>
        <% end %>
      </div>
      <% else %>
      <%# 反対済み %>
      <div class='col'>
        <%= link_to answer_question_path(question.id, 1) ,class: "btn btn-lg btn-primary thema", method: :post do %>
        賛成する
        <span class="badge badge-pill badge-light"><%= Answer.where(question_id: question.id, answer: true).count%></span>
        <% end %>
      </div>
      <div class='col'>
        <button class="btn-lg btn-secondary thema">反対済み <span class="badge badge-pill badge-light"><%= Answer.where(question_id: question.id, answer: false).count%></span></button>
      </div>
      <% end %>

    </div>
  </div>
</div>
<% end %>

app/views/shared/_question_result_index.html.erb
<% @questions_result.each do |question| %>


<div class="continer DivLink  p-1 bg-white rounded shadow">
  <div class='main'>
    <div class='row'>

      <div class="col-4">・区分</div>
      <div class='col-8'>
        <% if question.section.include? "ビ" %>
        <div class='section b'>ビ</div>
        <% end %>

        <% if question.section.include? "情" %>
        <div class='section j'>情</div>

        <% end %>
        <% if question.section.include? "医" %>
        <div class='section i'>医</div>
        <% end %>

        <% if question.section.include? "公" %>
        <div class='section g'>公</div>
        <% end %>

        <% if question.section.include? 'イ' %>
        <div class='section e'>イ</div>
        <% end %>
      </div>
    </div>
    <div class='row'>
      <div class='col-4'>・件名</div>
      <div class="col-8">
        <b><%= question.title %></b>
      </div>
    </div>
    <div class='row'>
      <div class='col-4'>・内容</div>
      <div class="col-8">
        <%= question.content %>
      </div>
    </div>
    <div class='row'>
      <div class='col-4'>・終了日</div>
      <div class="col-8">
        <%= question.end_date%>
      </div>
    </div>
    <div class='row'>
      <div class='col'>
        <button class="btn-lg btn-primary thema">賛 成 <span class="badge badge-pill badge-light"><%= Answer.where(question_id: question.id, answer: true).count%></span></button>

      </div>
      <div class='col'>
        <button class="btn-lg btn-danger thema">反 対 <span class="badge badge-pill badge-light"><%= Answer.where(question_id: question.id, answer: false).count%></span></button>
      </div>
    </div>
  </div>
</div>
<% end %>