config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'persons/thema'
  get 'persons/question'
  resources :questions
  resources :posts do
    resources :microposts
  end

  get '/questions_result', to: 'questions#result_index'
  post '/posts/:post_id/microposts/:id/like', to: 'microposts#like', as: :like
  post '/questions/:id/answer/:answer_id', to: 'questions#answer', as: :answer_question
  root 'static_pages#home'

  get '/users', to: 'users/registrations#new'

  get   '/help',    to: 'static_pages#help'
  get   '/contact', to: 'static_pages#contact'
  get   '/about',   to: 'static_pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
end

app/models/micropost.rb
# frozen_string_literal: true

class Micropost < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_rich_text :content
  has_many :likes, dependent: :destroy
  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/microposts_controller.rb
# frozen_string_literal: true

class MicropostsController < ApplicationController
  def index
    @post = Post.select('title', 'section', 'end_date').find(params[:post_id])
    @microposts = Micropost.where(post_id: params[:post_id])
    @like = Like.where(user_id: current_user.id, post_id: params[:post_id])
    @like_counts = Like.where(post_id: params[:post_id]).count
  end

  def show
    post = Post.find(params[:post_id])
    @micropost = post.microposts.find params[:id]
  end

  def edit
    @micropost = Micropost.find params[:id]
    unless current_user.id == @micropost.user_id
      flash[:danger] = 'あなたの提案投稿ではないので編集できません'
      redirect_to 'index'

    end
  end

  def update
    @micropost = Micropost.find(params[:id])
    if @micropost.update(micropost_params)
      flash[:success] = '提案投稿を編集しました'
      redirect_to post_microposts_path(params[:post_id])
    else

      render 'edit'
    end
  end

  def new
    @post = Post.find(params[:post_id])
    @micropost = @post.microposts.new
  end

  def create
    @post = Post.find(params[:post_id])
    params[:micropost][:user_id] = current_user.id
    @micropost = @post.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = 'あなたの提案を投稿しました'

      redirect_to "/posts/#{@post.id}/microposts"
    else
      render 'new'
    end
  end

  def destroy
    @microposts = Micropost.where(post_id: params[:post_id])
    micropost = Micropost.find(params[:id])
    if current_user.id == micropost.user_id
      micropost.destroy
      flash[:success] = '削除しました'
      redirect_to post_microposts_path params[:post_id]
    else
      flash[:danger] = 'あなたの投稿ではないので削除できません'
      render 'index'
    end
  end

  def like
    @microposts = Micropost.where(post_id: params[:post_id])
    if Like.where(user_id: current_user.id, micropost_id: params[:id], post_id: params[:post_id]).any?
      like = Like.find_by(user_id: current_user.id, micropost_id: params[:id], post_id: params[:post_id])
      like.destroy
      flash[:danger] = '提案の支持を解除しました'
      redirect_to post_microposts_path params[:post_id]
    else
      Like.create(user_id: current_user.id, micropost_id: params[:id], post_id: params[:post_id])
      # @microposts = Micropost.where(post_id: params[:post_id])
      flash[:success] = '提案を支持しました'
      redirect_to post_microposts_path params[:post_id]
    end
  end

  private

  def micropost_params
    params.require(:micropost).permit(:title, :content, :user_id)
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/edit.html.erb
<h2>Microposts#編集</h2>
<%= form_with(model: @micropost, local: true, url: post_micropost_path(@micropost.post_id, @micropost.id), method: :patch ) do |f| %>
<%= render "shared/error_messages", object: f.object %>
<div class="field">
  <%= f.label :title, "・タイトル" %>
  <%= f.text_field :title %>
</div>
<div class="field">
  <%= f.rich_text_area :content %>
</div><br>

<%= f.submit "編集", class: "btn btn-lg btn-primary btn-block"%>
<% end %>

app/views/microposts/index.html.erb
<h2>テーマ/<%= @post.title %><small><small><%= @microposts.count %> 件の提案</small></small></h2>
<div id="main">
  <div class="new-post">
    投票期限 : <%= @post.end_date %><br>
    <p class="division" style="display: inline;">対象区分 :
      <div class='div' style="display: inline;">
        <% if @post.section.include? "ビ" %>
        <div class='section b'>ビ</div>
        <% end %>

        <% if @post.section.include? "情" %>
        <div class='section j'>情</div>

        <% end %>
        <% if @post.section.include? "医" %>
        <div class='section i'>医</div>
        <% end %>

        <% if @post.section.include? "公" %>
        <div class='section g'>公</div>
        <% end %>

        <% if @post.section.include? 'イ' %>
        <div class='section e'>イ</div>
        <% end %>
      </div>
      <div>
        総投票数 : <span class="get"><%= @like_counts %></span> 票
      </div>
    </p>
  </div>

  <% if @post.end_date >= Date.today %>



  <div class="new-micropost"><%= link_to "新規に提案する", new_post_micropost_path(params[:post_id]), class: "aaa btn btn-lg btn-primary"  %></div>
  <% @microposts.each do |micropost| %>
  <% like = @like.where(micropost_id: micropost.id) %>
  <div class='content'>
    <% if user_signed_in? && current_user.id == micropost.user_id %>
    <%= link_to '編集', edit_post_micropost_path(params[:post_id], micropost.id), class: "post_btn continer  bg-white shadow-sm" %>

    <%= link_to '削除', post_micropost_path(params[:post_id], micropost.id), method: :delete, data: { confirm: '本当に削除してもよろしですか?' }, class: "post_btn continer  bg-white shadow-sm" %>
    <% end %>
    <div class="continer DivLink  p-1 bg-white rounded shadow">


      <div class="row">
        <div class='col-2'>
          ・タイトル
        </div>
        <div class='col-10'>
          <h3><%= micropost.title %></h3>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class='col-2'>
          ・提案内容
        </div>
        <div class='col-10'>
          <%= micropost.content %>
        </div>
      </div>
      <div class="row">

        <div class='col'>
          <% if like.any? %>
          <%= link_to '提案の支持を解除', like_path(params[:post_id], micropost.id), class: "btn btn-lg btn-secondary thema", method: :post %>
          <% else %>
          <%= link_to '提案を支持する!!', like_path(params[:post_id], micropost.id), class: "btn btn-lg btn-primary thema", method: :post %>
          <% end %>
        </div>
      </div>

    </div>
  </div>
  <% end %>
  <% else %>
  <% like_max = Like.where(post_id: params[:post_id]).group(:micropost_id).count.values.max %>

  <% @microposts.each do |micropost| %>
  <% like = @like.where(micropost_id: micropost.id) %>

  <% like_count = Like.where(micropost_id: micropost.id).count %>
  <div class='content'>
    <div class="continer DivLink  p-1 bg-white rounded shadow">


      <div class="row">
        <div class='col-2'>
          ・<span class="get"><%= like_count %></span><small>／<%= @like_counts %>票中</small>
        </div>
        <div class='col-10'>
          <h3><%= micropost.title %></h3>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class='col-2'>
          ・提案内容
        </div>
        <div class='col-10'>
          <%= micropost.content %>
        </div>
      </div>
      <div class="row">

        <div class='col'>
          <% if like_max == like_count %>
          <%#  if like.any? %>
          <button class="btn-gree thema btn-lg">
            この提案が最も多く支持されました!!</button>
          <% end %>
        </div>
      </div>

    </div>


  </div>
  <% end %>

  <% end %>

app/views/microposts/new.html.erb
<h2><%= "テーマ:「#{@post.title}」への提案" %></h2>
<%= form_with(model: @micropost, local: true, url: post_microposts_path(@micropost.post_id), method: :post ) do |f| %>
<%= render "shared/error_messages", object: f.object %>
<div class="field">
  <%= f.label :title, "・タイトル" %>
  <%= f.text_field :title %>
</div>
<p class="field">
  <%# <%= f.label :content %>
  <%= f.rich_text_area :content, class: "content-area" %>
</p>

<%= f.submit "投稿", class: "btn btn-lg btn-primary btn-block"%>
<% end %>

app/views/microposts/show.html.erb
<h2>Microposts#show</h2>
<p>Find me in app/views/microposts/show.html.erb</p>
<%= @micropost.title %>
<%= @micropost.content %>