config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'persons/thema'
  get 'persons/question'
  resources :questions
  resources :posts do
    resources :microposts
  end

  get '/questions_result', to: 'questions#result_index'
  post '/posts/:post_id/microposts/:id/like', to: 'microposts#like', as: :like
  post '/questions/:id/answer/:answer_id', to: 'questions#answer', as: :answer_question
  root 'static_pages#home'

  get '/users', to: 'users/registrations#new'

  get   '/help',    to: 'static_pages#help'
  get   '/contact', to: 'static_pages#contact'
  get   '/about',   to: 'static_pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
end

app/views/layouts/_footer.html.erb
  <footer class='navbar navbar-fixed-bottom footer'>

    <small>(C)2020 H.M</small>
    <nav>
      <ul class="nav ">
        <li><%= link_to "プロフィール", about_path %></li>
        <li><%= link_to "お問い合わせ", contact_path %></li>
        <li><%= link_to "大原News", "https://school.o-hara.ac.jp/kashiwa/newslist/", target: "blank", rel: "noopener" %></li>

        <% if login? %>
        <li><%= link_to "アカウント", user_path(@current_user) %></li>
        <li><%= link_to "変更・修正", edit_user_path(@current_user)%></li>
        <% end %>
      </ul>
    </nav>

  </footer>

app/views/layouts/_head.html.erb
<head>
  <title><%= full_title( yield(:title) ) %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_pack_tag "application", media: "all", "data-turbolinks-track": "reload" %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md sticky-top navbar-dark mb-4" style="background-color: #0060d0;">
  <a href='/' id="logo"><span class="navbar-brand"><span id="logo-init">S</span>uggest!!</span></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#Navbar" aria-controls="Navbar" aria-expanded="false" aria-label="ナビゲーションの切替">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="Navbar">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item dropdown <%= active?("home") %> <%= active_controller? "posts" %> ">
        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" id="navbarDropdown" role="button" aria-haspopup="true" aria-expanded="false">
          テーマ
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "テーマ投稿", new_post_path, class: "dropdown-item" %>
          <%= link_to "テーマ一覧", root_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">その他(未実装)</a>
        </div>
      </li>

      <li class="nav-item dropdown  <%= active_controller? "questions" %> ">
        <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          アンケート
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "アンケート投稿", new_question_path, class: "dropdown-item" %>
          <%= link_to "集計中一覧", questions_path, class: "dropdown-item" %>
          <%= link_to "終了・結果", questions_result_path, class: "dropdown-item" %>

          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">その他(未実装)</a>
        </div>
      </li>

      <li class="nav-item <%= active? "about" %> ">
        <%= link_to "概要", about_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>





      <li class="nav-item dropdown <%= active_controller? "persons" %> ">
        <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          アカウント
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "アカウント情報",  edit_user_registration_path(current_user), class: "dropdown-item" %>
          <%= link_to "投稿した提案テーマ", persons_thema_path, class: "dropdown-item" %>
          <%= link_to "投稿したアンケート", persons_question_path, class: "dropdown-item" %>

          <div class="dropdown-divider"></div>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "dropdown-item" %>

        </div>
      </li>

    </ul>
    <div class="my- my-md-0">
      <%= link_to "#{current_user.name}さん", edit_user_registration_path(current_user) %>
    </div>
    <% else %>
    <li class="nav-item <%= active? "new" %> ">
      <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
    </li>
    <li class="nav-item <%= active? "new" %> ">
      <%= link_to "アカウント作成", new_user_registration_path, class: "nav-link" %>
    </li>
    </ul>
    <% end %>


    <%# <form class="form-inline my-2 my-md-0">
      <input class="form-control mr-sm-2" type="search" placeholder="検索..." aria-label="検索...">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">検索</button>
    </form>%>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<%= render "layouts/head" %>

<body>
  <%# deviseのFlashメッセージ %>
  <%= render "layouts/header" %>

  <div class='wrapper container'>

    <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <%# <%= success_msg %>
    <%# <%= danger_msg %>
    <%= yield %>
  </div>
  <%= debug(params) if Rails.env.development? %>
  <%# <script>
    import {
      AttachmentUpload
    } from "./attachment_upload"

    addEventListener("trix-attachment-add", event => {
      const {
        attachment,
        target
      } = event

      if (attachment.file) {
        const upload = new AttachmentUpload(attachment, target)
        upload.start()
      }
    })
    import {
      DirectUpload
    } from "activestorage"

    export class AttachmentUpload {
      constructor(attachment, element) {
        this.attachment = attachment
        this.element = element
        this.directUpload = new DirectUpload(attachment.file, this.directUploadUrl, this)
      }

      start() {
        this.directUpload.create(this.directUploadDidComplete.bind(this))
      }

      directUploadWillStoreFileWithXHR(xhr) {
        xhr.upload.addEventListener("progress", event => {
          const progress = event.loaded / event.total * 100
          this.attachment.setUploadProgress(progress)
        })
      }

      directUploadDidComplete(error, attributes) {
        if (error) {
          throw new Error(`Direct upload failed: ${error}`)
        }

        this.attachment.setAttributes({
          sgid: attributes.attachable_sgid,
          url: this.createBlobUrl(attributes.signed_id, attributes.filename)
        })
      }

      createBlobUrl(signedId, filename) {
        return this.blobUrlTemplate
          .replace(":signed_id", signedId)
          .replace(":filename", encodeURIComponent(filename))
      }

      get directUploadUrl() {
        return this.element.dataset.directUploadUrl
      }

      get blobUrlTemplate() {
        return this.element.dataset.blobUrlTemplate
      }
    }
  </script> %>
</body>

</html>